// haozi-ui-react/src/pages/sys/role/index.tsx
import React, {useEffect, useState} from 'react'
import {Button, Card, Form, Input, Modal, Space, Table} from 'antd'
import {useCrud} from '@/hooks/useCrud'
import {useUserStore} from '@/stores'
import type {SysRole} from '@/types/sys/role'
import type {ColumnsType} from 'antd/es/table'
import AddOrUpdate from './addOrUpdate.tsx'


const RoleManagement: React.FC = () => {
  const [form] = Form.useForm()
  const { hasPermission } = useUserStore()
  const [modalVisible, setModalVisible] = useState(false)
  const [editId, setEditId] = useState<number | undefined>()

  const {
    state,
    getDataList,
    resetQueryForm,
    currentChangeHandle,
    sizeChangeHandle,
    deleteHandle,
  } = useCrud({
    dataListUrl: '/sys/role/page',
    deleteUrl: '/sys/role',
    queryForm: {
      name: '',
      code: '',
      status: undefined,
    },
  })

  useEffect(() => {
    getDataList()
  }, [])

  const confirmDelete = (id: number) => {
    Modal.confirm({
      title: '确认删除',
      content: '确定要删除这条记录吗？',
      onOk: () => deleteHandle(id),
    })
  }

  const handleAdd = () => {
    setEditId(undefined)
    setModalVisible(true)
  }

  const handleEdit = (id: number) => {
    setEditId(id)
    setModalVisible(true)
  }

  const handleModalSuccess = () => {
    setModalVisible(false)
    getDataList()
  }

  const handleModalCancel = () => {
    setModalVisible(false)
  }



  const columns: ColumnsType<SysRole> = [
    {
      title: '角色名称',
      dataIndex: 'name',
      key: 'name',
      width: 150,
    },
    {
      title: '操作',
      key: 'action',
      width: 200,
      fixed: 'right' as const,
      render: (_, record) => (
        <Space size="small">
          {hasPermission('sys:role:update') && (
            <Button
              type="link"
              size="small"
              onClick={() => handleEdit(record.id)}
            >
              编辑
            </Button>
          )}
          {hasPermission('sys:role:delete') && (
            <Button
              type="link"
              size="small"
              danger
              onClick={() => confirmDelete(record.id)}
            >
              删除
            </Button>
          )}
        </Space>
      ),
    },
  ]

  
  return (
    <Card>
      <Form form={form} layout="inline" style={{ marginBottom: 16 }}>
        <Form.Item name="name">
          <Input placeholder="角色名称" allowClear style={{ width: 150 }} />
        </Form.Item>
        <Form.Item>
          <Space>
            {hasPermission('sys:role:save') && (
              <Button
                type="primary"
                onClick={handleAdd}
              >
                新增
              </Button>
            )}
            <Button
              type="primary"
              onClick={() => {
                state.queryForm = form.getFieldsValue()
                state.page = 1
                getDataList()
              }}
            >
              查询
            </Button>
            <Button onClick={resetQueryForm}>
              重置
            </Button>
          </Space>
        </Form.Item>
      </Form>

      <Table
        columns={columns}
        dataSource={state.dataList}
        rowKey="id"
        loading={state.loading}
        pagination={{
          current: state.page,
          pageSize: state.limit,
          total: state.total,
          showSizeChanger: true,
          showQuickJumper: true,
          showTotal: total => `共 ${total} 条记录`,
          pageSizeOptions: state.pageSizes,
          onChange: currentChangeHandle,
          onShowSizeChange: sizeChangeHandle,
        }}
        scroll={{ x: 1200 }}
        bordered
      />

      <AddOrUpdate
        visible={modalVisible}
        id={editId}
        onSuccess={handleModalSuccess}
        onCancel={handleModalCancel}
      />
    </Card>
  )
}

export default RoleManagement

// haozi-ui-vue/src/views/sys/role/index.vue
<template>
	<el-card>
		<el-form :inline="true" :model="state.queryForm" @keyup.enter="getDataList()">
			<el-form-item>
				<el-input v-model="state.queryForm.name" placeholder="名称" clearable></el-input>
			</el-form-item>
			<el-form-item>
				<el-button @click="getDataList()">查询</el-button>
			</el-form-item>
			<el-form-item>
				<el-button v-auth="'sys:role:save'" type="primary" @click="addOrUpdateHandle()">新增</el-button>
			</el-form-item>
		</el-form>
		<el-table v-loading="state.dataListLoading" :data="state.dataList" border style="width: 100%" @selection-change="selectionChangeHandle">
			<el-table-column prop="name" label="名称" header-align="center" align="center"></el-table-column>
			<el-table-column label="操作" fixed="right" header-align="center" align="center" width="200">
				<template #default="scope">
					<el-button v-auth="'sys:role:update'" type="primary" link @click="addOrUpdateHandle(scope.row.id)">菜单权限</el-button>
					<el-button v-auth="'sys:role:delete'" type="primary" link @click="deleteHandle(scope.row.id)">删除</el-button>
				</template>
			</el-table-column>
		</el-table>
		<el-pagination
			:current-page="state.page"
			:page-sizes="state.pageSizes"
			:page-size="state.limit"
			:total="state.total"
			layout="total, sizes, prev, pager, next, jumper"
			@size-change="sizeChangeHandle"
			@current-change="currentChangeHandle"
		>
		</el-pagination>
		<!-- 弹窗, 新增 / 修改 -->
		<add-or-update ref="addOrUpdateRef" @refresh-data-list="getDataList"></add-or-update>
	</el-card>
</template>

<script setup lang="ts" name="SysRoleIndex">
import {useCrud} from '@/hooks'
import {reactive, ref} from 'vue'
import AddOrUpdate from './add-or-update.vue'
import {IHooksOptions} from '@/hooks/interface'

const state: IHooksOptions = reactive({
	dataListUrl: '/sys/role/page',
	deleteUrl: '/sys/role',
	queryForm: {
		name: ''
	}
})

const addOrUpdateRef = ref()
const addOrUpdateHandle = (id?: number) => {
	addOrUpdateRef.value.init(id)
}




const { getDataList, selectionChangeHandle, sizeChangeHandle, currentChangeHandle, deleteHandle } = useCrud(state)
</script>

<style scoped>

</style>
